#!/usr/bin/env python3
"""Generate the theme catalogue from Ghostty's own theme files.

Ghostty ships the iTerm2-Color-Schemes palettes. Rather than hand-copy a
handful, this reads every one and emits a single TypeScript module.

    git clone --depth 1 https://github.com/mbadolato/iTerm2-Color-Schemes.git
    python3 scripts/build-themes.py path/to/iTerm2-Color-Schemes/ghostty

The chrome colours (window, panels, borders) are derived from each theme's
background rather than hand-picked, so a 600-theme list stays consistent and
the window never clashes with the terminal inside it.
"""

import re
import sys
from pathlib import Path

KV = re.compile(r"^\s*([a-z0-9-]+)\s*=\s*(.+?)\s*$")
PALETTE = re.compile(r"^(\d+)\s*=\s*(#[0-9a-fA-F]{6})$")


def parse(path: Path) -> dict | None:
    """Reads one Ghostty theme file into a dict of colours."""
    out: dict[str, str] = {}
    palette: dict[int, str] = {}

    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        m = KV.match(line)
        if not m:
            continue
        key, value = m.group(1), m.group(2)
        if key == "palette":
            p = PALETTE.match(value)
            if p:
                palette[int(p.group(1))] = p.group(2).lower()
        elif value.startswith("#") and len(value) == 7:
            out[key] = value.lower()

    if "background" not in out or "foreground" not in out:
        return None
    if len(palette) < 16:
        return None

    out["palette"] = [palette[i] for i in range(16)]
    return out


def rgb(hex_colour: str) -> tuple[int, int, int]:
    h = hex_colour.lstrip("#")
    return int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)


def to_hex(r: int, g: int, b: int) -> str:
    clamp = lambda v: max(0, min(255, int(round(v))))
    return f"#{clamp(r):02x}{clamp(g):02x}{clamp(b):02x}"


def luminance(hex_colour: str) -> float:
    r, g, b = rgb(hex_colour)
    return (0.2126 * r + 0.7152 * g + 0.0722 * b) / 255


def shift(hex_colour: str, amount: float) -> str:
    """Moves a colour toward white (positive) or black (negative)."""
    r, g, b = rgb(hex_colour)
    if amount >= 0:
        return to_hex(r + (255 - r) * amount, g + (255 - g) * amount, b + (255 - b) * amount)
    return to_hex(r * (1 + amount), g * (1 + amount), b * (1 + amount))


def mix(a: str, b: str, t: float) -> str:
    ra, ga, ba = rgb(a)
    rb, gb, bb = rgb(b)
    return to_hex(ra + (rb - ra) * t, ga + (gb - ga) * t, ba + (bb - ba) * t)


def chrome(bg: str, fg: str) -> dict[str, str]:
    """Window colours derived from the terminal's own background, so the app
    frame and the terminal read as one surface at any of 600 themes."""
    dark = luminance(bg) < 0.5
    step = 0.06 if dark else -0.04

    return {
        "bg": shift(bg, -0.25 if dark else 0.35),
        "panel": bg,
        "panel2": shift(bg, step * 1.6),
        "border": shift(bg, step * 3.2),
        "fg": fg,
        "dim": mix(fg, bg, 0.35),
        "faint": mix(fg, bg, 0.58),
    }


def main() -> int:
    if len(sys.argv) < 2:
        print(__doc__, file=sys.stderr)
        return 2

    src = Path(sys.argv[1])
    themes = []

    for f in sorted(src.iterdir(), key=lambda p: p.name.lower()):
        if not f.is_file():
            continue
        parsed = parse(f)
        if not parsed:
            continue

        bg, fg = parsed["background"], parsed["foreground"]
        themes.append(
            {
                "name": f.name,
                "dark": luminance(bg) < 0.5,
                "background": bg,
                "foreground": fg,
                # Not every theme sets a cursor; the foreground is the
                # conventional fallback.
                "cursor": parsed.get("cursor-color", fg),
                "selectionBackground": parsed.get(
                    "selection-background", shift(bg, 0.18 if luminance(bg) < 0.5 else -0.12)
                ),
                "palette": parsed["palette"],
                "chrome": chrome(bg, fg),
            }
        )

    lines = [
        "// Generated by scripts/build-themes.py — do not edit by hand.",
        "//",
        "// Every theme Ghostty ships, which is the iTerm2-Color-Schemes set.",
        "// Chrome colours are derived from each background so the window frame",
        "// and the terminal read as one surface across all of them.",
        "",
        "import type { Theme } from './settings.svelte';",
        "",
        "export const THEMES: Theme[] = [",
    ]

    for t in themes:
        pal = ", ".join(f"'{c}'" for c in t["palette"])
        c = t["chrome"]
        lines.append(
            "  { "
            f"name: {t['name']!r}, dark: {'true' if t['dark'] else 'false'}, "
            f"background: '{t['background']}', foreground: '{t['foreground']}', "
            f"cursor: '{t['cursor']}', selectionBackground: '{t['selectionBackground']}', "
            f"palette: [{pal}], "
            f"chrome: {{ bg: '{c['bg']}', panel: '{c['panel']}', panel2: '{c['panel2']}', "
            f"border: '{c['border']}', fg: '{c['fg']}', dim: '{c['dim']}', faint: '{c['faint']}' }} "
            "},".replace("'", "'")
        )

    lines += ["];", ""]

    out = Path("src/lib/themes.ts")
    out.write_text("\n".join(lines), encoding="utf-8")

    dark = sum(1 for t in themes if t["dark"])
    print(f"{len(themes)} themes ({dark} dark, {len(themes) - dark} light) -> {out}")
    print(f"{out.stat().st_size // 1024} KB")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
